### ISSUE TITLE
need to access on glb_jobinfo() 

### ISSUE THREAD

**Issue by rhinosys** [IBMSpectrumComputing/lsf-python-api#11]
Hi,

I find into API glb_jobinfo()  this fonction. How to access this function with the LSF python. 
I dont find any declare fonction into the code.

https://www.ibm.com/support/knowledgecenter/SSWRJV_10.1.0/api_reference/index.html

Regards,

**Comment by PlatformLSF** [comment]
Hello rhinosys, the API glb_jobinfo() belongs to LSF License Scheduler. 
Currently we don't support APIs of LSF License Scheduler in LSF Python package.
