### ISSUE TITLE
expose bhist and bacct into the Python API

### ISSUE THREAD

**Issue by jordiblasco** [IBMSpectrumComputing/lsf-python-api#13]
I realized that bhist/bacct is not exposed in the Python API.
lsb.events doesn't seem to be the appropriate mechanism to get this data.

Any suggestion to get standard stats once each job is completed?

**Comment by adamsla** [comment]
Jordi,

We have an official offering to provide bhist capability using Elastic Search now.  It's called LSF Explorer.  We also have a number of customers who have extended the Python API to fetch data from the RTM solution.  RTM stores everything in a nicely partitioned database for upto 3 years.  The partition API is pretty strait forward, and it's just understanding the schema from there.

Do you have either of these solutions?

Larry

**Comment by mps111** [comment]
Does LSF Explorer work with LSF 10.1.0.4 ?

**Comment by wolfohyeah** [comment]
@mps111 Yes.

**Comment by xawangyd** [comment]
LSF Explorer can meet the requirement.
