### ISSUE TITLE
segmentation fault when invoking lsf.lsb_queueinfo

### ISSUE THREAD

**Issue by wolfohyeah** [IBMSpectrumComputing/lsf-python-api#14]
Hi, 
I'm trying to test the [example code](https://github.com/IBMSpectrumComputing/lsf-python-api/blob/master/examples/queue_info.py) in my python interpreter. When I invoke `lsf.lsb_queueinfo` api,  sometimes it keep printing '_lsf is down, please wait_' (I check my lsf cluster is working fine). Sometimes no error return but the next command 'queueInfo.queue' return the wrong queue name( invoked _short_ queue but return _analog_ queue name). Sometimes it prints 'segmentation fault(core dumped)' and then exit the interpreter.
```
>>> ....
>>>lsf.stringArray_setitem(strArr, 0, 'short')
>>>queueInfo = lsf.lsb_queueinfo(strArr,intp_num_queues,None,None,0)
>>>queueInfo.queue
```
This's my first time to use lsf api. Hope someone can help me with this issue. Thanks. 
[lsf 10.1.0.4, python 2.6.6 ]

**Comment by PlatformLSF** [comment]
Hi wolfohyeah,

Do you use the latest LSF Python API code ? 
You need rebuild & install LSF Python API package with your LSF environment.

Under the same condition, does bqueues work normally ?

**Comment by wolfohyeah** [comment]
@PlatformLSF Hi , thanks for reply. Yes I use the latest Python API. And the bqueues command works well at the same time. I will try to rebuild and install it as you suggest. Thanks .

**Comment by PlatformLSF** [comment]
This one should be the compatibility issue which is fixed by the latest code.

The solution is to use the static library liblsbstream.a to create _lsf.so.  
The compatibility issue will be gone if you use the new LSF Python API package to build with LSF 10.1.0.3 or later.
