### ISSUE TITLE
How to I get the results of bapp using the Python API?

### ISSUE THREAD

**Issue by slecrenski** [IBMSpectrumComputing/lsf-python-api#18]
I want to get the results of the LSF command bapp and retrieve the results using the Python API.  I cannot figure out how to do it using this API or even with the C api.

**Comment by adamsla** [comment]
@slecrenski, you can download the source code for all the LSF commands from the following link.  It shold included the bapp application https://www-945.ibm.com/support/fixcentral/swg/doSelectFixes?options.selectedFixes=lsf-10.1-build427553&continue=1.  Let me know if that is good enough.  I can ask the Dev team to provide an example if you would like to see the Python case still.

**Comment by slecrenski** [comment]
Yes please provide an example for the Python api.  In the meantime I will review the source.

**Comment by adamsla** [comment]
@PlatformLSF, can you please proide a bapp python example for @slecrenski?

**Comment by PlatformLSF** [comment]
@slecrenski 

You can get the latest code of master branch, build and install LSF Python API package again.

$ python **examples/disp_app.py**
LSF Clustername is : cluster1_boliu_1105
2 apps in the cluster.
No.0 app name : app1, description: No description provided.
No.1 app name : resizable, description: Enables running jobs resizable

Let me know if you have any concern.

**Comment by slecrenski** [comment]
ty.  I'll try it out later this morning.  

I can't seem to find the lsb_appInfo function in the online api documentation reference.  Maybe it could be added?  https://www.ibm.com/support/knowledgecenter/SSWRJV_10.1.0/api_reference/index.html

**Comment by PlatformLSF** [comment]
Sure.

I'll ask ID to add it if there isn't any special reason.
