### ISSUE TITLE
Add get_queue_info_all() to api

### ISSUE THREAD

**Issue by slecrenski** [IBMSpectrumComputing/lsf-python-api#20]
I found this at one point on the IBM Platform LSF portals.

Can these be appended to the bottom of lsf.i?

```Python

 PyObject * get_queue_info_all() {
     struct queueInfoEnt *queueinfo;
     char **resreq = NULL;
     int numqueues = 0;
     int options = 0;

     queueinfo = lsb_queueinfo(resreq,             // Return queries as C queueInfoEnt*
                   &numqueues, NULL, 0, options);

     PyObject *result = PyList_New(numqueues);     // Create PyObject * to get C returns
     int i;
     for (i = 0; i < numqueues; i++) {             // Save queries in a loop to result
         PyObject *o = SWIG_NewPointerObj(SWIG_as_voidptr(&queueinfo[i]),
                                          SWIGTYPE_p_queueInfoEnt, 0 | 0 );
         PyList_SetItem(result,i,o);
     }

     return result;
 }

```

**Comment by PlatformLSF** [comment]
Sure. I can add it into lsf.i in the next update.

**Comment by slecrenski** [comment]
An issue should not be closed until the code is merged with the master.  Thanks.  I did not write this code so I cannot submit a pull request.  But please notice the char **resreq = NULL change to eliminate the compiler warning/error.

**Comment by PlatformLSF** [comment]
OK

Let's close it when the code is updated.

**Comment by adamsla** [comment]
Has this been completed yet?

**Comment by xawangyd** [comment]
Added the get_queue_info_all function in the [commit #118](https://github.com/IBMSpectrumComputing/lsf-python-api/commit/d4092a20977a889594be4c9cf547116ba0a7cd98)

**Comment by xawangyd** [comment]
Maintainer can help to close the issue.

**Comment by PlatformLSF** [comment]
Completed the enhancement.

**Comment by adamsla** [comment]
Thanks guys.
