### ISSUE TITLE
ls_load returning junk values along with hostName

### ISSUE THREAD

**Issue by rajathpatil** [IBMSpectrumComputing/lsf-python-api#22]
On retrieving hostName from ls_load it gives output something like this 
hostname.com\x00e\x02\x00d\x08\x00<e\x08\x00i\x1e\x00e\x04\x00d\x08\x00<e\x0b\x00o\x19\x00\x01e\x0c\x00e\x08

which is treated as garbage value.

I want the output to be as hostname.com like the output from lsb_hostinfo on retrieving host

How do i ignore the junk values that it is returning?

**Comment by PlatformLSF** [comment]
Hi rajathpatil,

Which LSF version do you use ? 
Did you rebuild LSF Python API package to try ?

**Comment by PlatformLSF** [comment]
Maybe you can try the latest code of LSF Python API package. (master branch)

Does the command lsload work normally ?

**Comment by rajathpatil** [comment]
I'm using the latest version. Yes lsload command works properly

**Comment by rajathpatil** [comment]
j = 0
lsload_names = None
num_lsload = lsf.new_intp() #New pointer variable
lsf.intp_assign(num_lsload, 0) #Assign value to pointer variable
lsload_data = lsf.ls_load(None, num_lsload, 256, None)
all_lsload_data = lsf.hostLoadArray_frompointer(lsload_data)

When i query for all_lsload_data.hostName it returns hostname.com\x00e\x02\x00d\x08\x00<e\x08\x00i\x1e\x00e\x04\x00d\x08\x00<e\x0b\x00o\x19\x00\x01e\x0c\x00e\x08

**Comment by rajathpatil** [comment]
Hi,

Any update on this? 

Thanks

**Comment by PlatformLSF** [comment]
You may try the script below. 
Python don't think NULL is the end of a string. That's why the garbage characters are displayed. 
And the option used in ls_load() should not be 256. It should be 0 if you don't know the meaning of it.
------------------------------------------------------------------
$ cat lsload.py
from pythonlsf import lsf
import ctypes

def printHostInfo():
    if lsf.lsb_init("test") > 0:
        return -1;

    intp_nhosts = lsf.new_intp()
    lsf.intp_assign(intp_nhosts, 0)
    hostsdata = lsf.ls_load(None, intp_nhosts, 0, None)
    nhosts = lsf.intp_value(intp_nhosts)
    all_lsload_data = lsf.hostLoadArray_frompointer(hostsdata)

    print("{} hosts in the cluster.".format(nhosts))

    for i in range(nhosts) :
        host = all_lsload_data[i]
        hostname = ctypes.cast( host.hostName, ctypes.c_char_p)
        print('No.{} host name : {}'.format(i, hostname.value))

    return 0

if __name__ == '__main__':
    print("LSF Clustername is : {}".format(lsf.ls_getclustername()))
    printHostInfo()

**Comment by rajathpatil** [comment]
Yes its working. Thanks much :)

**Comment by rajathpatil** [comment]
I just had one other question, if this function 'hostLoadArray_frompointer' is not available then is there a way to get the data from 'hostLoad *'.

On the other hand if a getter method as such is not defined then how can we get the data?

**Comment by PlatformLSF** [comment]
168 %array_class(struct queueInfoEnt, queueInfoEntArray);
169 %array_class(struct hostInfoEnt, hostInfoEntArray);
**170 %array_class(struct hostLoad, hostLoadArray);**

We use %array_class to provide the interface to hostLoad structure. The %array_class is provided by SWIG. We should follow the usage of this syntax.

**Comment by rajathpatil** [comment]
Thank you.

I'm relatively new to this, can you please share an example of how to use these interfaces(%array_class)?

**Comment by PlatformLSF** [comment]
http://www.swig.org/Doc2.0/Python.html

You may refer to this one. LSF Python API library is based on SWIG.

**Comment by rajathpatil** [comment]
I'm getting few errors when i'm running 'swig -python lsf.i'

lsf.i:259: Error: Unable to find 'lsf.h'
lsf.i:260: Error: Unable to find 'lsbatch.h'

**Comment by PlatformLSF** [comment]
Please follow the instructions in README.md.

**Comment by xawangyd** [comment]
It is in relation to the usage of SWIG.
