### ISSUE TITLE
ImportError: No module named '_lsf'

### ISSUE THREAD

**Issue by IstrateRoxana** [IBMSpectrumComputing/lsf-python-api#24]
I try to install the python-lsf-api following the readme you propose, but i get this error:

```
$ python3 -c "from pythonlsf import lsf"
Traceback (most recent call last):
  File "lsf-python-api/pythonlsf/lsf.py", line 16, in swig_import_helper
    fp, pathname, description = imp.find_module('_lsf', [dirname(__file__)])
  File "/opt/at10.0/lib64/python3.5/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_lsf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "lsf-python-api/pythonlsf/lsf.py", line 26, in <module>
    _lsf = swig_import_helper()
  File "lsf-python-api/pythonlsf/lsf.py", line 18, in swig_import_helper
    import _lsf
ImportError: No module named '_lsf'
```

Python version is 3.5
My system is: Linux zhcc026 3.10.0-957.10.1.el7.ppc64le #1 SMP Thu Feb 7 07:19:03 UTC 2019 ppc64le ppc64le ppc64le GNU/Linux

I did the python3.5 setup.py build and install --user.

Is there an obvious thing i forgot to set?

**Comment by PlatformLSF** [comment]
Python can not find the LSF library _lsf.so in your environment．

Can you install LSF Pthon API package by root account ?

**Comment by IstrateRoxana** [comment]
No, unfortunately, i can not. I do not have sudo rights in my system. What else can we do?

**Comment by thomasgas** [comment]
Same issue...can you solve this?

**Comment by lovaulonze** [comment]
I have two comments concerning this issue.
1) I also happen to encounter this issue when I was running the testing command (`python -c "from pythonlsf import lsf"`) inside the directory of the git repo (i.e. same level as the `setup.py`). 

   This will give you exactly the same error of "No module named _lsf". Running the command outside the package directory maybe solve the issue.

2) Usually the cluster admin should have the _lsf.so somewhere as described by the `profile.lsf`. You probably need to search for where `profile.lsf` is depending on your system. For instance in my case it is "$LSF_ENVDIR/profile.lsf"
  
     You need to run `source /path/to/profile.lsf` before the installation to ensure the environmental variables can be found. 

In my case the python-api can be installed without system admin privileges (python 3.7.1, LSF version 10.1).

**Comment by haris860** [comment]
> I have two comments concerning this issue.
> 
> 1. I also happen to encounter this issue when I was running the testing command (`python -c "from pythonlsf import lsf"`) inside the directory of the git repo (i.e. same level as the `setup.py`).
>    This will give you exactly the same error of "No module named _lsf". Running the command outside the package directory maybe solve the issue.
> 2. Usually the cluster admin should have the _lsf.so somewhere as described by the `profile.lsf`. You probably need to search for where `profile.lsf` is depending on your system. For instance in my case it is `$LSF_ENVDIR/profile.lsf`
>    You need to run `source /path/to/profile.lsf` before the installation to ensure the environmental variables can be found.
> 
> In my case the python-api can be installed without system admin privileges (python 3.7.1, LSF version 10.1).

I was able to install lsf by source /path/to/profile.lsf but when I try to import lsf then I get the same error again.

**Comment by PeteClapham** [comment]
Sorry guys, I'm seeing the same. The above worked against 9.1.x but is failing against 10.1 ->.
My output is:

pc7@farm5-head2:/tmp/lsf-python-api$ python3
Python 3.7.4 (default, Aug 13 2019, 14:20:12)
[GCC 7.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pythonlsf import lsf
Traceback (most recent call last):
  File "/tmp/lsf-python-api/pythonlsf/lsf.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/software/python-3.7.4/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pythonlsf._lsf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/lsf-python-api/pythonlsf/lsf.py", line 17, in <module>
    _lsf = swig_import_helper()
  File "/tmp/lsf-python-api/pythonlsf/lsf.py", line 16, in swig_import_helper
    return importlib.import_module('_lsf')
  File "/software/python-3.7.4/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_lsf'
>>> quit()

Environment wise, the usual LSF components are defined as expected.

pc7@farm5-head2:/tmp/lsf-python-api$ env|grep LSF
LSF_SERVERDIR=/usr/local/lsf/10.1/linux3.10-glibc2.17-x86_64/etc
LSF_ENVDIR=/usr/local/lsf/conf
LSF_BINDIR=/usr/local/lsf/10.1/linux3.10-glibc2.17-x86_64/bin
LSF_LIBDIR=/usr/local/lsf/10.1/linux3.10-glibc2.17-x86_64/lib

I get the same, whether building into a venv or as root into a centrally exported  /software/python -3.x area.

Any thoughts much appreciated
Pete

**Comment by adamsla** [comment]
For batch query, and load query, you need the LSF_ENVDIR set.  However, you must also either have the LD_LIBRARY_PATH set to the LSF *.so files can be found.  For batch submission, you also need the LSF_SERVERDIR set so that the Systems eauth can be found.  Otherwise, jobs submission and control will not work.

Having not looked at the code, I don't know if it is forking LSF commands, but if it is, you should add the LSF_BINDIR to the path as well.

Since this is more of a question of use, rather than a bug.  I will close.  I would be nice though if one of you could do a pull request on the README.md to provide more tips on using.  Even a complementary *.md file with a link from the README.md would help.
