### ISSUE TITLE
passing pointer-to-pointer struct issue with lsb_limitfInfo

### ISSUE THREAD

**Issue by okskmk2** [IBMSpectrumComputing/lsf-python-api#25]
Hello
In python API, how to pass pointer-to-pointer struct to lsb_limitfInfo

Below is C API
`int lsb_limitInfo( limitInfoReq *req, limitInfoEnt **limitItemRef, int *size, struct lsInfo* lsInfo)`

Please let me know passing limitInfoEnt ** in Python Script

**Comment by PlatformLSF** [comment]
Hi Eunsung,

You may refer to the example/disp_limit.py of the latest code for passing double pointers into LSF API.
