### ISSUE TITLE
ImportError on mosquito_loop 

### ISSUE THREAD

**Issue by khahmed** [IBMSpectrumComputing/lsf-python-api#26]
Hi,
 
I'm trying the LSF python api  from https://github.com/IBMSpectrumComputing/lsf-python-api .I  built it on Power and am trying to run the example. I'm getting this error. Any ideas of what might be wrong? Not sure where the mosquito comes from.Looked it up and looks like something from MQTT.
 
[root@master examples]# python queue_info.py
Traceback (most recent call last):
 File "queue_info.py", line 1, in <module>
   from pythonlsf import lsf
 File "/usr/lib64/python2.7/site-packages/pythonlsf/lsf.py", line 26, in <module>
   _lsf = swig_import_helper()
 File "/usr/lib64/python2.7/site-packages/pythonlsf/lsf.py", line 22, in swig_import_helper
   _mod = imp.load_module('_lsf', fp, pathname, description)
ImportError: /usr/lib64/python2.7/site-packages/pythonlsf/_lsf.so: undefined symbol: mosquitto_loop
[root@master examples]# ls -l /usr/lib64/python2.7/site-packages/pythonlsf/_lsf.so
 
 
[root@master examples]# uname -a
Linux master 4.14.0-115.8.1.el7a.ppc64le #1 SMP Thu May 9 14:45:13 UTC 2019 ppc64le ppc64le ppc64le GNU/Linux
[root@master examples]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.6 (Maipo)

**Comment by PlatformLSF** [comment]
The libmosquitto.so will be loaded by LSF library dynamically. You may put it into $LSF_LIBDIR.

**Comment by adamsla** [comment]
@PlatformLSF, I saw you deleted your comment.  I was going to say, that if this is the procedure, and it does seem odd, it should be clear in the README.md for the tool.  Something does not seem right though.

**Comment by PlatformLSF** [comment]
The **_lsf.so** file does not exist in your directory /usr/lib64/python2.7/site-packages/pythonlsf/
It means that you do not install lsf python API succeed, please follow the steps in readme file to compile and install lsf python api
