### ISSUE TITLE
Links to documentation require updating

### ISSUE THREAD

**Issue by hpcjb** [IBMSpectrumComputing/lsf-python-api#29]
developerWorks is being closed, apparently. The link currently 'works' in that you are sent to the correct page, but you are immediately bounced to the new community site, which doesn't have the information.

The wiki will need to be migrated and the links updated, in order to remain relevant.

**Comment by adamsla** [comment]
What links are you talking about @hpcjb ?

**Comment by adamsla** [comment]
Never mind.  Thanks for the heads up.  Discussing with our information development people right now.

**Comment by asm582** [comment]
Hello @adamsla,  The links still don't work in the introduction section, attaching the screenshot of the section in which links do not work:

![Screen Shot 2020-06-05 at 4 58 20 PM](https://user-images.githubusercontent.com/5898557/83922220-f3a1a980-a74d-11ea-97d8-69316d3048c7.png)

**Comment by shashwatsahay** [comment]
Hi,

Is there any plan to update the links?

**Comment by adamsla** [comment]
I've sent a note to the Development management.  They were going to get these updated after the 10.1.0.10 release, which is not done.  Let me check back again.

**Comment by hpcjb** [comment]
Thanks!
