### ISSUE TITLE
SegmentationFault after upgrade to LSF10

### ISSUE THREAD

**Issue by rajathpatil** [IBMSpectrumComputing/lsf-python-api#33]
Hi Developers,

We are facing an issue with the APIs after upgrading to LSF 10. 
On running the code, it's resulting in 'Segmentation Fault'.
Have rebuild and reinstalled the LSF Python API package but still, the issue persists. 

I can send across a copy of the script if required, please suggest at the earliest.

**Comment by PlatformLSF** [comment]
Can you provide some information of your environment , such as Linux OS version, run uname -m command to get machine type. 

Which API did you hit Segmentation Fault?
Can your provide some error messages?

Please append a copy of the script here.

Thanks

**Comment by PlatformLSF** [comment]
Hi, 
Can you provide your LSF version?

**Comment by PlatformLSF** [comment]
Hi rajathpatil,
Is there any update  ?

**Comment by rajathpatil** [comment]
Hi @PlatformLSF,

Apologies for the delay.
Linux version: 3.10.0-693.el7.x86_64
LSF Version: 10.1.0.10
OS: 7.4 (Maipo)

Error o/p: Segmentation fault (core dumped)

I believe this code snippet is causing the segmentation fault:

`def get_bhost_data():
    lsf.lsb_init('bhosts')
    bhost_names = None
    num_bhosts = lsf.new_intp() #New pointer variable
    lsf.intp_assign(num_bhosts, 0) #Assign value to pointer variable
    bhost_data = lsf.lsb_hostinfo(bhost_names, num_bhosts) 
    all_bhost_data = lsf.hostInfoEntArray_frompointer(bhost_data)    
    
    return all_bhost_data, num_bhosts

def get_lsload_data():
    lsf.lsb_init('lsload')    
    cs_num_lsload = lsf.new_intp() #New pointer variable
    lsf.intp_assign(cs_num_lsload, 0) #Assign value to pointer variable
    cs_lsload_data = lsf.ls_load("cs", cs_num_lsload, 0, None)
    all_cs_lsload_data = lsf.hostLoadArray_frompointer(cs_lsload_data)
    
    gui_num_lsload = lsf.new_intp() #New pointer variable
    lsf.intp_assign(gui_num_lsload, 0) #Assign value to pointer variable
    gui_lsload_data = lsf.ls_load("gui", gui_num_lsload, 0, None)
    all_gui_lsload_data = lsf.hostLoadArray_frompointer(gui_lsload_data)

    return all_cs_lsload_data, cs_num_lsload, all_gui_lsload_data, gui_num_lsload

def get_avail_resources(all_bhost_data, all_lsload_data, ls_num_hosts, b_num_hosts, server_type):
    host_info[server_type] = {}
    host_info[server_type]['avail_cores'] = {}
    host_info[server_type]['avail_mem'] = {}
    
    for j in range(0, lsf.intp_value(ls_num_hosts)):
        for i in range(0, lsf.intp_value(b_num_hosts)):
            if(all_bhost_data[i].host.split("\x00")[0] == all_lsload_data[j].hostName.split("\x00")[0]):
                host_info[server_type]['avail_cores'][all_bhost_data[i].host] = int(all_bhost_data[i].maxJobs) - int(all_bhost_data[i].numJobs)
                host_info[server_type]['avail_mem'][all_bhost_data[i].host] = int(lsf.floatArray_getitem(all_lsload_data[j].li,lsf.MEM))
     
    return host_info

    all_bhost_data, b_num_hosts = get_bhost_data()
    
    #Get lsload data
    all_cs_lsload_data, cs_num_lsload, all_gui_lsload_data, gui_lsload_data = get_lsload_data()
    
    #Get available resource like cores and memory available
    host_information = get_avail_resources(all_bhost_data, all_cs_lsload_data, cs_num_lsload, b_num_hosts, "cs")
    host_information = get_avail_resources(all_bhost_data, all_gui_lsload_data, gui_lsload_data, b_num_hosts, "gui")
`

On calling get_avail_resources, i get the error. The same code was working fine on LSF 9.1 version.

**Comment by PlatformLSF** [comment]
Thanks rajathpatil
I can not reproduce on my environment.

Some questions:

Is the **i** variable out of range of the **_all_bhost_data_** object array ?

Can you print _**lsf.intp_value(b_num_hosts)**_ ? and the length of _**all_bhost_data**_ to compare the value?

Does your program go to the first **_for_** loop and go to the second **_for_** loop? 

Does the below condition still work? or this line cause segment fault, since the **i** is out of range?
_**all_bhost_data[i].host.split("\x00")[0] == all_lsload_data[j].hostName.split("\x00")[0]**_

**Comment by PlatformLSF** [comment]
If it is the i is out of range

You can did a quick test with the below code:

```
from pythonlsf import lsf

def get_bhost_data():
    lsf.lsb_init('bhosts');
    bhost_names = None;
    
    num_bhosts = lsf.new_intp(); #New pointer variable
    lsf.intp_assign(num_bhosts, 0); #Assign value to pointer variable
    bhost_data = lsf.lsb_hostinfo(bhost_names, num_bhosts);
    all_bhost_data = lsf.hostInfoEntArray_frompointer(bhost_data);

    return all_bhost_data, num_bhosts;

all_bhost_data, b_num_hosts = get_bhost_data();

print lsf.intp_value(b_num_hosts)

for i in range(0, lsf.intp_value(b_num_hosts)):
    print all_bhost_data[i].host;

```
Here is the result that I run with LSF 10.1.0.10
```
# python host.py 
1
domlinux-1
```

**Comment by PlatformLSF** [comment]
If upgrade to LSF 10.1.0.10, the root user does not have permission to call LSF API and run LSF commands.
Suggest use non-root user to execute your python application.

If use root to run my above python application, get below results:

```
[root@domlinux-1 examples]# python host.py 
0
[root@domlinux-1 examples]# 
```
Cannot get hosts with root user.

**Comment by PlatformLSF** [comment]
There are some security enhancements in LSF 10.1.0.10,  the root user cannot run some LSF commands and call some LSF APIs.
