### ISSUE TITLE
How can I get the execution host?

### ISSUE THREAD

**Issue by laurentvm** [IBMSpectrumComputing/lsf-python-api#34]
So far, 

I am able to get machine from which the job has been sumitted but not on which machine the job is running
```
lx114
_60dda77f71550000_p_p_char
84
```

I guess the hostnames are in the **char, but how to read it from python ?

**Comment by PlatformLSF** [comment]
The hostnames  are in the **char, you can read as below:
```
for i in range(0,numhosts):
        hoststr += lsf.stringArray_getitem(submithosts, i) + ""
        print("submitHost<%s>" %(hoststr))
```
