### ISSUE TITLE
Library Documentation

### ISSUE THREAD

**Issue by manistal** [IBMSpectrumComputing/lsf-python-api#4]
Great to have a python API for this, but I can't find alot of documentation on the C code and haven't been able to find any documentation on the Python. 

Along the same thread I'd like to request that the example code is cleaned up a bit and thorough comments are added to explain what's going on and show other options. In addition it'd be great to see an example on polling the queue to see if a job that you've submitted is finished since that's a really common use case for some customers.

**Comment by PlatformLSF** [comment]
Hello manistal,
You may reference the code of LSF commands for using LSF APIs. 
Please contact your SUPPORT for the code package.
