### ISSUE TITLE
Examples don't work properly

### ISSUE THREAD

**Issue by decandia50** [IBMSpectrumComputing/lsf-python-api#8]
There are C syntax and comments in the file which are not valid python; i.e. you don't need semicolons, and // is not used for comments, # is.

**Comment by decandia50** [comment]
Sorry, I meant to point out this part of the code, the above portion was where the trivial syntax errors were.

    intp_num_queues = lsf.new_intp();
    lsf.intp_assign(intp_num_queues, 1);
    strArr = lsf.new_stringArray(1);
    #print lsf.intp_value(intp_num_queues);
    lsf.stringArray_setitem(strArr, 0, queue_name);

**Comment by PlatformLSF** [comment]
Fixed.
