### ISSUE TITLE
question regarding the esub

### ISSUE THREAD

**Issue by maverick-xinwei** [IBMSpectrumComputing/lsf-python-api#9]
Hi , 

The option '-a <program name>'  could be used with bsub to run some esub applicatioin.  How can I do the same thing in python by using the api ? 

Thanks and best regards,
Xinwei

**Comment by adamsla** [comment]
I had asked the same question.  It's some magic in the bsub code that is not quite exposed easily in the API.  However, this introduces a possible security issue.  Let me ping @PlatformLSF.  @PlatformLSF, can you respond to this.  It is a security issue.

**Comment by PlatformLSF** [comment]
There are no variables in relation to the ‘-a’ option in the _struct submit_  in lsbatch.h header.
Do not support via LSF python API  to run some esub application.
